name: ibvstudio first workflow

on: [push]

jobs:
  explore-github-actions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Show Current Directory
      run: pwd

    - name: List Files in Project
      run: ls -la

    - name: Display Current Date and Time
      run: date
